# Векторы и матрицы

In [1]:
import numpy as np

внутрь конструктора numpy.array() можно передавать любой итерируемый объект

In [2]:
np.array((1, 2, 3, 4)) # кортеж (1, 2, 3, 4)

array([1, 2, 3, 4])

In [3]:
print(np.array((1, 2, 3, 4)))

[1 2 3 4]


In [4]:
np.array((1))

array(1)

In [8]:
print(np.array((1))) #просто значение 1

1


In [9]:
print(np.array((1,))) # кортеж из 1 элемента

[1]


In [11]:
np.array((True, 2., 3, '4')) # все элементы стали типа строка

array(['True', '2.0', '3', '4'], dtype='<U32')

**На вход подаётся список чисел.**

Создайте и сохраните:

в переменную V1 Numpy вектор из этих чисел в том же порядке
в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
в переменную V3 Numpy вектор из этих чисел в обратном порядке
в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход
Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [24]:
import numpy as np
s = input()

V1 = np.array([float(i) for i in s.split(',')])
print(V1)
V2 = np.array((V1[-2],))
print(V2)
V3 = V1[::-1]
print(V3)
V4 = V1[::3]
print(V4)
V5 = np.array(range(len(V1)))
print(V5)

 1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[9.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[ 1.  4.  7. 10.]
[0 1 2 3 4 5 6 7 8 9]


На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

**Используя векторные операции создайте и сохраните:**

в переменную V1 Numpy вектор с числами из 1 строки
в переменную V2 Numpy вектор с числами из 2 строки
в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке
Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [25]:
import numpy as np
s1 = input()
s2 = input() 

#считываем, данные указав separator, а также dtype, так как по-умолчанию стоит float
V1 = np.fromstring(s1, dtype=np.int, sep=', ')
V2 = np.fromstring(s2, dtype=np.int, sep=', ')
V3 = V1 + V2
V4 = V1[::2] * V2[-1::-2]

 3 3
 4 4


На вход подаётся 2 набора целых чисел.

**Создайте вектор V такой, что он будет содержать числа из 1 набора, делящиеся нацело на предпоследнее число из 2 набора и разделённые на это число.**

Если таких чисел не найдётся, то вектор V будет пустым (т.е. не будет содержать элементов).

 

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [28]:
import numpy as np

v1 = np.fromstring(input(), sep = ', ')
v2 = np.fromstring(input(), sep = ', ')

V = v1[v1 % v2[-2] == 0] / v2[-2]
print(V)

 1, 2, 3, 4, 5, 6
 1, 2, 3, 4


[1. 2.]


## площадь треугольника

В этой задаче нам даны 3 переменные: A1, A2, A3. Каждая содержит вектор с 2 координатами соответствующей вершины треугольника.

Найдите площадь треугольника и выведите её на печать.

 

Если все 3 точки лежат на одной прямой, то площадь треугольника равна 0.

 

Ответ проверяется с точностью до 4 знака после запятой.

In [34]:
import numpy as np

def len_a(a1, a2):
    #длина отрезка по координатам точек a1(x1, y1) и a2(x2, y2)
    #((a1[0] - a2[0])**2 + (a1[1] - a2[1])**2) ** 0.5
    return sum((a1-a2)**2)**0.5 

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

# пл. треугольника по формуле герона
a = len_a(A1, A2)
b = len_a(A2, A3)
c = len_a(A1, A3)

p = (a + b + c) / 2

S = (p * (p - a) * (p - b) * (p - c)) ** 0.5

print(S)

17.999999999999993


Переменная M1 содержит Numpy матрицу.

Произведите операции последовательно:

**1. Замените значения в предпоследней строке на значения по формуле:**

sin(x*pi / 6), где x - старое значение

**2. Замените значения в предпоследнем столбце на значения по форуме:**

e ** x 

Результат запишите в переменную M2


Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу

In [39]:
M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

import numpy as np
M1[-2] = np.sin(M1[-2] * np.pi / 6)

M1[:, -2] = np.exp(M1[:, -2])

M2 = np.copy(M1)

[[1.00000000e+00 2.00000000e+00 2.00855369e+01 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 4.03428793e+02 0.00000000e+00]
 [0.00000000e+00 5.00000000e-01 1.64872127e+00 1.22464680e-16]
 [7.00000000e+00 8.00000000e+00 8.10308393e+03 0.00000000e+00]]
[0.00000000e+00 5.00000000e-01 1.64872127e+00 1.22464680e-16]


# Решение задач NumPy-100

In [40]:
import numpy as np

In [41]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/natasha/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/natasha/anac

In [42]:
np.__version__

'1.16.4'

## 3.1
Считайте число n

Создайте в переменной Z Numpy вектор из нулей длины n.

In [44]:
import numpy as np

n = int(input())
Z = np.zeros(n)
print(Z)

 5


[0. 0. 0. 0. 0.]


## 3.2

Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.
Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)



Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [57]:
import numpy as np

s = [int(i) if i.isdigit() else i for i in input().split()]

if not str(s[-1]).isdigit():
    s_type = np.dtype(s[-1])
    s_shape = tuple(s[:-1:])
else:
    s_type = np.float64
    s_shape = tuple(s)

Z = np.zeros(s_shape, dtype=s_type)

print(Z)



 2 4 3 bool


[[[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]]


## 4. Посчитайте размер матрицы Z в байтах и выведите его на печать.

Чтобы узнать размер (в байтах) 1 элемента матрицы используйте атрибут https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.itemsize.html

Примечание. В этой задаче не нужно ничего считывать - матрица Z уже заполнена.

In [65]:

#Z = np.zeros((10,10))
Z = np.array([1,2,3], dtype=np.float64)
#print(Z.data.nbytes)
print(Z.nbytes)

24


## 5. Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array.

In [ ]:
import numpy as np
np.info(np.add)
np.info(np.array)

## 6 Считайте 2 числа:

n - размер Numpy вектора
x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.
Сохраните вектор в переменную Z.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [72]:
import numpy as np

n = int(input())
x = int(input())

Z = np.zeros(n)
Z[x] = 1

print(Z)

 5
 3


[0. 0. 0. 1. 0.]


In [73]:
import numpy as np

Z = np.eye(1, int(input()), int(input())).ravel()

print(Z)

 5
 3


[0. 0. 0. 1. 0.]


In [77]:
# Функция eye возвращает матрицу с единичками на к-атой диагонали:
np.eye(4, 3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

ravel -  возвращает плоский массив

## 7 Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [79]:
import numpy as np

n, m = int(input()), int(input())
Z = np.arange(n, m+1)

print(Z)

 3
 9


[3 4 5 6 7 8 9]


## 8. Дан вектор Z. "Разверните" его.



Примечание. В этой задаче не нужно ничего выводить на печать или считывать. Только развернуть уже созданный вектор Z.

In [80]:
Z = Z[::-1]

## 9. Считайте 3 числа:
n - количество элементов матрицы
m и l - размеры матрицы (число строк и столбцов соответственно)
**Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).**
Гарантируется, что m*l = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [89]:
import numpy as np

n = int(input())
size = np.fromstring(input(), dtype=np.int, sep=' ')
Z = np.arange(n).reshape(size)
print(Z)

 12
 3 4


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 10.1
Дан вектор Z

**Запишите в переменную NonZerros индексы ненулевых элементов.**

Используйте функцию https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nonzero.html



Примечание. В этой задаче не нужно ничего считывать или выводить на печать. Матрица Z уже готова, просто создайте NonZerros. 

In [91]:
import numpy as np

Z = [1, 0, 2, 0, 3, 0, 4]
NonZerros = np.nonzero(Z)

print(NonZerros)

(array([0, 2, 4, 6]),)


## 10.2
Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

**Выведите на печать список чисел из этой матрицы, которые больше 3.**

In [101]:
import numpy as np

Z = np.array([1, 2, 3, 4])
print(Z > 3)

print(Z[Z > 3])

[False False False  True]
[4]


## 11. Считайте число n

**Создайте единичную матрицу размера n, сохраните результат в переменную Z.**



Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [103]:
import numpy as np

n = int(input())
Z = np.eye(n)

print(Z)

 4


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 12. Считайте 3 числа: n, m, l.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
**Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.**


Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [109]:
import numpy as np

np.random.seed(42)
n, m, l = map(int, input().split())
Z = np.random.random((n, m, l))

print(Z)

 2 2 2


[[[0.37454012 0.95071431]
  [0.73199394 0.59865848]]

 [[0.15601864 0.15599452]
  [0.05808361 0.86617615]]]


## 13. Создайте матрицу n*m из случайных чисел (от 0 до 1).
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [112]:
import numpy as np

np.random.seed(42)
n, m = map(int, input().split())
Z = np.random.random((n, m))

print(np.min(Z))
print(np.max(Z))

 2 3


0.15599452033620265
0.9507143064099162


## 14. Среднее значение для всей матрицы
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).

**Выведите на печать значение среднего для всей матрицы.**

In [113]:
import numpy as np

np.random.seed(42)
n, m = map(int, input().split())
Z = np.random.random((n, m))

print(np.mean(Z))

 2 3


0.4946533353407266


## 14.1 Найдите среднее значение для каждого из столбцов.
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).

**Найдите среднее значение для каждого из столбцов.**

Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).

In [116]:
import numpy as np

np.random.seed(42)
n, m = map(int, input().split())
Z = np.random.random((n, m))

mean_Z = np.mean(Z, axis=0)

print(np.min(mean_Z))
print(np.max(mean_Z))

 3 4


[0.37722459 0.60492713 0.27022068 0.81158149]
0.270220682758469
0.8115814940446553


## 15
Считайте 2 числа: n, m.

**Создайте матрицу размера n*m такую что:**

    На границе матрицы будут стоять 1
    
    Внутри матрицы будут стоять 0

Сохраните матрицу в переменную Z.

In [121]:
import numpy as np

n, m = map(int, input().split())
Z = np.zeros((n,m))
Z[0] = np.ones(m)
Z[n-1] = np.ones(m)
Z[:, 0] = np.ones(n)
Z[:, m-1] = np.ones(n)

print(Z)

 10 10


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [124]:
import numpy as np

#Z = np.ones(tuple(map(int, input().split())))
n, m = map(int, input().split())
Z = np.ones((n,m))

Z[1:-1, 1:-1] = 0

print(Z)

 10 10


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. Имеется матрица Z. Добавьте вокруг имеющихся значений матрицы "забор" из 0.

In [140]:
import numpy as np

Z = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Z = np.pad(Z, ((1, 1), (1, 1)), mode='constant', constant_values=0)

print(Z)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


## 17. numpy.nan

In [130]:
import numpy
numpy.isnan(numpy.nan)

True

In [131]:
import numpy
numpy.nan in set([numpy.nan])

True

In [132]:

numpy.nan - numpy.nan

nan

In [133]:


numpy.nan == numpy.nan

False

In [134]:
0 * numpy.nan

nan

In [135]:
numpy.inf > numpy.nan

False

In [136]:

0.3 == 3 * 0.1

False

## 18.1 Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.

Считайте число n.

**Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.**
Сохраните матрицу в переменную Z.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [144]:
import numpy as np

n = int(input())

diag = np.arange(1, n+1)
Z = np.diag(diag)

print(Z)

 4


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## 18.2 Диагональная матрица со сдвигом диагонали

Считайте 2 числа:

x - сдвиг для единственной ненулевой диагонали в матрице.
k - верхняя граница для интервала чисел на диагонали (т.е. если k = 5, то на диагонали будут стоять числа 1, 2, 3, 4 и 5)
Договоримся о значениях x:

x = 0 - это главная диагональ матрицы
x<0 - диагональ сдвигается вниз на |x| ячеек (если x = -1, то первая не нулевая ячейка будет с координатами (1,0))
x>0 - диагональ сдвигается вправо на |x| ячеек (если x = 1, то первая ненулевая ячейка будет с координатами (0,1))


Обратите внимание, что размер матрицы изменяется в зависимости от сдвига, т.к. вам надо уместить все числа от 1 до k!
Сохраните такую матрицу в переменную Z.



Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [150]:
import numpy as np

x, k = map(int, input().split())

d = np.arange(1, k+1)

Z = np.diag(d, x)

print(Z)

 1 5


[[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


## 19 (21) Матрица в шахматном порядке


Считайте 2 числа: n, m.
Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.
0 - "чёрное"
1 - "белое"
Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).
Матрицу сохраните в переменную Z.

In [156]:
import numpy as np

x, k = map(int, input().split())

Z = np.ones((n, m))
Z[::2,::2] = 0
Z[1::2,1::2] = 0

print(Z)

 3 3


[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


## 20. Функция numpy.unravel_index

Если у нас есть матрица (или numpy массив большей размерности), то её можно представить в линейном виде:



Идея в том, что можно каждому элементу матрицы можно поставить в соответствие индекс.
Функция numpy.unravel_index проводит обратную операцию - по индексу элемента определяет его "координаты" в матрице.



Даны:

индекс i
numpy массив Z
Определите "координаты" элемента с индексом i в Z и выведите кортеж с координатами на печать.



Примечание. В этой задаче не нужно ничего считывать. i и Z уже заполнены.

In [166]:
import numpy as np

i = 5
Z = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

print(np.unravel_index(i, Z.shape))

(1, 1)


In [177]:
# принцип работы
# сначала массив как бы разворачивается в линию - в плоский, фенкция ravel
# затем белем индекс i из линейного массива
# сворачиваем линейный массив в другой с размерностью shape
# выводим новые координаты элемента с индексом i из линейного массива в новом массиве

import numpy as np

i = 5
Z = np.array([[ 20,  13,  24,  31],
       [ 34,  15,  60,  27],
       [ 84,  29, 10, 21]])

Z_lin = np.ravel(Z)
print(Z_lin)
print(Z_lin[i])

Z = np.reshape(Z, (3,4))
print(Z)
print(np.unravel_index(i, Z.shape))

Z = np.reshape(Z, (4,3))
print(Z)
print(np.unravel_index(i, Z.shape))



[20 13 24 31 34 15 60 27 84 29 10 21]
15
[[20 13 24 31]
 [34 15 60 27]
 [84 29 10 21]]
(1, 1)
[[20 13 24]
 [31 34 15]
 [60 27 84]
 [29 10 21]]
(1, 2)


## 22 Нормализация
Используйте формулу $x_{new} = \frac {x - \mu}{\sigma}$


где

$x$ - старое значение

$x_{new}$  - новое значение

$μ$ - среднее значение (по всей матрице)

$σ$ - стандартное отклонение (по всей матрице)

для того чтобы "нормализовать" матрицу.

Мы пока не будем углубляться в математическую суть этой операции, важно лишь, что оба значения для матрицы могут быть вычислены стандартными функциями numpy и вам не нужно звать на помощь статистику)

Переменная Y содержит исходную матрицу

В переменную Z сохраните её "нормализованный" вид, округлив каждое значение в матрице до 2 знака после запятой с помощью numpy.around.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [182]:
import numpy as np

Y = [[1, 2], [2, 1]]

Z = (Y - np.mean(Y))/np.std(Y)
Z = np.around(Z, decimals=1)

print(Z)

[[-1.  1.]
 [ 1. -1.]]


## 24.1 Скалярное произведение векторов
Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.

A и B могут содержать как int, так и float.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать Z.

In [184]:
import numpy as np

#A = np.array([1.5, 2.5, 3.5])
#B = np.array([4, 5, 6])

A = np.array([1, 3, 5, 7, 9])
B = np.array([-2, 4, -6, 8, -10])

Z = np.dot(A, B)

print(Z)

-54


## 24.2 Умножение матриц
Даны 2 матрицы: A и B.

Найдите произведение матриц и сохраните его в переменную Z.

Если найти произведение матриц невозможно, то запишите в Z строку:

Упс! Что-то пошло не так...

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать Z.

In [188]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [11.5],
    [12.5],
    [13.5]
])

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [11.5, 12.5, 13.5]
])

if A.shape[1] == B.shape[0]:
    Z = np.dot(A, B)
else:
    Z = 'Упс! Что-то пошло не так...'

print(Z)

Упс! Что-то пошло не так...


## 25. Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

Примечание. В этой задаче не нужно ничего выводить на печать. Только заменить некоторые элементы Z.

In [203]:
Z = np.arange(11)

Z[(3<Z) & (Z<9)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 26. Что выведет на печать код:


In [204]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


Получается по доке, что в случае numpy.sum второй параметр(-1) это ось (axis) и она не складывается никак с первым параметром, а лишь указывает направление как считать. При  axis = -1 считает по осям в обратном порядке, начиная с последней до первой. Здесь массив линейный, ось одна, и этот параметр ни на что не влияет.

## 27. Какие из операций возможны (не приведут к ошибке)?

Предположим, Z - целочисленный вектор, например:

Z = np.array([1, 2, 3, 4, 5, 6, 7])


In [205]:
Z = np.array([1, 2, 3, 4, 5, 6, 7])

In [206]:
2 << Z >> 2

array([ 1,  2,  4,  8, 16, 32, 64])

In [207]:
Z <- Z

array([False, False, False, False, False, False, False])

In [208]:
Z**Z

array([     1,      4,     27,    256,   3125,  46656, 823543])

In [210]:
Z/1/1

array([1., 2., 3., 4., 5., 6., 7.])

In [211]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j])

In [212]:
np.array(0) / np.array(0)

/Users/natasha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [213]:
np.array(0) // np.array(0)

/Users/natasha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [216]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [217]:
array([inf])

array([inf])

In [219]:
array([-2.14748365e+09])

array([-2.14748365e+09])

In [218]:
inf

inf

## 29. Округлите их до целых и результат запишите в переменную Z.

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого
отрицательные числа округляем всегда вниз до целого
0 остаётся 0


Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [225]:
A = np.array([-3.1, -5.9, 0, 2.2, 9.8])

Z = np.copy(A)
Z[Z>0] = np.ceil(Z[Z>0])
Z[Z<0] = np.floor(Z[Z<0])

print(Z)

[-4. -6.  0.  3. 10.]


In [227]:
# вариант покороче
Z = np.where(A>0,np.ceil(A),np.floor(A))
print(Z)

[-4. -6.  0.  3. 10.]


## 30. Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.
Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [228]:
A = np.array([0, 9, 7, 1, 3, 7, 5, 2, 5, 1])
B = np.array([3, 1, 3, 7, 4, 1, 8, 1, 1, 8])

Z = np.intersect1d(A, B)
print(Z)

[1 3 7]


## 31. numpy.seterr - устанавливает как обрабатываются ошибки

\# Suicide mode on

В Numpy можно предусмотреть различное поведение в случае ошибок (а не только то, что мы наблюдали в задаче 28). Для этого используется функция https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.seterr.html

Отключите вывод всех ошибок (это довольно опасное поведение)

In [238]:
numpy.seterr('ignore')

numpy.arange(3)/0

array([nan, inf, inf])

In [241]:
numpy.seterr('raise')

numpy.arange(3)/0

FloatingPointError: divide by zero encountered in true_divide

In [247]:
numpy.seterr('warn')

{'divide': 'raise', 'over': 'raise', 'under': 'raise', 'invalid': 'raise'}

In [248]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
    

False


/Users/natasha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [249]:
numpy.seterr('raise')

{'divide': 'warn', 'over': 'warn', 'under': 'warn', 'invalid': 'warn'}

## 33 работа с датой

In [250]:
np.datetime64('today')

numpy.datetime64('2020-04-05')

In [251]:
np.datetime64('nat')

numpy.datetime64('NaT')

In [252]:
np.datetime64('tomorrow')

ValueError: Error parsing datetime string "tomorrow" at position 0

In [253]:
np.datetime64('nat')+1

numpy.datetime64('NaT')

In [254]:
np.datetime64('today')+1

numpy.datetime64('2020-04-06')

In [255]:
np.datetime64('nat')-1

numpy.datetime64('NaT')

In [256]:
np.datetime64('yesterday')

ValueError: Error parsing datetime string "yesterday" at position 0

In [257]:
np.datetime64('today')-1

numpy.datetime64('2020-04-04')

In [258]:
np.datetime64('now')

numpy.datetime64('2020-04-05T05:47:23')

## 34 Массив из дат
1-я входная строка - год (опционально месяц и день) в формате ISO начала отсчёта

2-я входная строка - год (опционально месяц и день) в формате ISO окончания отсчёта

Составьте список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.

Пример - 2005-02-25, где

2005 - год
02 - месяц
25 - день

Запишите результат в переменную Z

In [261]:
import numpy as np

Z = np.arange(input(), input(), dtype='datetime64[D]')
print(Z)

 2016-07
 2016-08


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 36. Существует по крайней мере 5 способов получить из вектора случайных float чисел вектор чисел только с целой частью:

Целочисленное деление и векторные операции

Округление "вниз"

Округление "вверх" и вычет 1 (важно, что этот способ работает только для "случайных" чисел. Если число УЖЕ целое, то такая манипуляция приведёт к получению числа на 1 меньше исходного, т.е. ошибке)

Приведение к целочисленному типу

"Усечение" или округление в сторону нуля с помощью функции https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.trunc.html

In [265]:
Z = np.random.uniform(0,10,10)
# array([1.45929438, 7.67176895, 4.30717228, 3.87291767, 1.12721643, 2.44432376, 9.03933531, 2.09715241, 2.61381042, 4.27172585])
print(Z)

#1
X = Z - Z%1
print('1:', X)

#2
X = np.floor(Z)
print('2:', X)

#3
X = np.ceil(Z)-1
print('2:', X)

#4
X = Z.astype(int)
print('4:', X)

#5
X = np.trunc(Z)
print('5:', X)

[6.07544852 1.70524124 0.65051593 9.48885537 9.65632033 8.08397348
 3.04613769 0.97672114 6.84233027 4.40152494]
1: [6. 1. 0. 9. 9. 8. 3. 0. 6. 4.]
2: [6. 1. 0. 9. 9. 8. 3. 0. 6. 4.]
2: [6. 1. 0. 9. 9. 8. 3. 0. 6. 4.]
4: [6 1 0 9 9 8 3 0 6 4]
5: [6. 1. 0. 9. 9. 8. 3. 0. 6. 4.]


## 37.1 Создайте матрицу размера n*m такую, что каждая её строка содержит числа от k до k+m-1 (с шагом 1).

На вход подаётся 2 строки:

1-я строка содержит 2 натуральных числа: n, m

2-я строка содержит число k

Создайте матрицу размера n*m такую, что каждая её строка содержит числа от k до k+m-1 (с шагом 1).

Ответ запишите в переменную Z

In [16]:
import numpy as np

n, m = map(int, input().split())
k = float(input())

Z = np.tile(np.arange(k, k+m), n).reshape((n, m))

print(Z)

 3 5
 -4


[[-4. -3. -2. -1.  0.]
 [-4. -3. -2. -1.  0.]
 [-4. -3. -2. -1.  0.]]


## 37.2 Создайте матрицу размера n*m такую, что каждый её столбец содержит числа от k до k+n-1 (с шагом 1).
На вход подаётся 2 строки:

1-я строка содержит 2 натуральных числа: n, m

2-я строка содержит число k

Создайте матрицу размера n*m такую, что каждый её столбец содержит числа от k до k+n-1 (с шагом 1).

Ответ запишите в переменную Z

In [19]:
import numpy as np

n, m = map(int, input().split())
k = float(input())

#создаю матрицу другого размера столбцы на строки: m на n
Z = np.tile(np.arange(k, k+n), m).reshape((m, n))

#транспонирую матрицу
Z = Z.T
print(Z)

 3 4
 -1


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]]
