# Векторы и матрицы

In [1]:
import numpy as np

внутрь конструктора numpy.array() можно передавать любой итерируемый объект

In [2]:
np.array((1, 2, 3, 4)) # кортеж (1, 2, 3, 4)

array([1, 2, 3, 4])

In [3]:
print(np.array((1, 2, 3, 4)))

[1 2 3 4]


In [4]:
np.array((1))

array(1)

In [8]:
print(np.array((1))) #просто значение 1

1


In [9]:
print(np.array((1,))) # кортеж из 1 элемента

[1]


In [11]:
np.array((True, 2., 3, '4')) # все элементы стали типа строка

array(['True', '2.0', '3', '4'], dtype='<U32')

**На вход подаётся список чисел.**

Создайте и сохраните:

в переменную V1 Numpy вектор из этих чисел в том же порядке
в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
в переменную V3 Numpy вектор из этих чисел в обратном порядке
в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход
Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [24]:
import numpy as np
s = input()

V1 = np.array([float(i) for i in s.split(',')])
print(V1)
V2 = np.array((V1[-2],))
print(V2)
V3 = V1[::-1]
print(V3)
V4 = V1[::3]
print(V4)
V5 = np.array(range(len(V1)))
print(V5)

 1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[9.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[ 1.  4.  7. 10.]
[0 1 2 3 4 5 6 7 8 9]
